a = input (" enter a:")
b = input ("enter b:")
A= int(a)+ int(b)
S=int(a)- int(b)
M=int(a)* int(b)
D=int(a)/ int(b)
print ("the sum is",A)
print("substraction is", S)
print("multiplication is",M)
print("division is",D)
